eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org:
      springframework:
        data: debug
server:
  port: 8081
spring:
  application:
    name: review-service
  data:
    mongodb:
      database: test_reviews
      host: localhost
      port: 27017
